name: Verify

on:
  push:
    branches: '**'

jobs:
  release:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Use node_modules cache
        uses: actions/cache@v4
        id: modules-cache
        with:
          path: '**/node_modules'
          key: ${{ secrets.CACHE_VERSION }}-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ secrets.CACHE_VERSION }}-${{ runner.os }}-modules-

      - name: Install deps
        run: yarn install --immutable

      - name: Test
        run: yarn test
